### ISSUE TITLE
"Skip execution of action on startup" stopped working

### ISSUE THREAD

**Issue by Destroy666x** [WarmUpTill/SceneSwitcher#1010]
**Describe the bug**
That checkbox in macro settings stopped working.

**To Reproduce**
1. Enable `Skip execution of action on startup` for a macro with condition like `Streaming stopped`
2. Macro is executed anyways

**Expected behavior**
It shouldn't be

**Logs**
https://obsproject.com/logs/f6GA5wtEy9eDcuND

**Version information**
 - OS: Windows 10
 - OBS Version: 30.0.2
 - Plugin Version: latest new template branch
 
**Additional context**
\-

**Comment by WarmUpTill** [comment]
Thanks a lot for pointing that out!
That seems to be related to https://github.com/WarmUpTill/SceneSwitcher/commit/77528520d93a9fb02044cbf5c28468a6f761a396.

Apparently before the actual settings are loaded the save/ load callback is first called with an empty data string by OBS.
Since the default state of the plugin changed from "stopped" to "started" the plugin will now start running with empty settings / default values.

Later on the save / load callback is called again - this time with the actual saved data, which is to be loaded.
But as the plugin is now already running the "skip execution on actions on startup" check fails.

I will try to dig into why OBS is doing that and implement a workaround.

**Comment by WarmUpTill** [comment]
I think I understand what is happening.
When OBS is calling `OBSBasic::LoadData()` it also calls `ClearSceneData()`. [1] 
This triggers a `OBS_FRONTEND_EVENT_SCENE_COLLECTION_CLEANUP` event.
This in turn triggers the scene switcher to call the `SaveSceneSwitcher()` function with empty data. [2]
Which was introduced with https://github.com/WarmUpTill/SceneSwitcher/commit/dcae0e8e8be4e6fb4733f8b23ee67d6ff0a9e07f to avoid old settings being carried over to new scene collections.
In the end the _real_ data is loaded at [3].

So the fix will be to simply skip this step on OBS startup.
Should be fixed with https://github.com/WarmUpTill/SceneSwitcher/pull/1014/commits/0609828d38d063e330e29693a1bdbf569f67df5b.

[1] https://github.com/obsproject/obs-studio/blob/master/UI/window-basic-main.cpp#L1112
[2] https://github.com/WarmUpTill/SceneSwitcher/blob/master/lib/advanced-scene-switcher.cpp#L692-L693
[3] https://github.com/obsproject/obs-studio/blob/master/UI/window-basic-main.cpp#L1321

**Comment by Destroy666x** [comment]
Thanks, confirming it works.
