### ISSUE TITLE
Crash in plugin built from source

### ISSUE THREAD

**Issue by flakywanderer** [WarmUpTill/SceneSwitcher#1160]
**Describe the bug**
When the plugin is built from source, opening the plugin's settings page crashes OBS Studio

**To Reproduce**
1. Build and install obs-advanced-scene-switcher from source (in my case, via [https://aur.archlinux.org/packages/obs-advanced-scene-switcher](https://aur.archlinux.org/packages/obs-advanced-scene-switcher))
2. Open the settings for advanced scene switcher in the "tools" menu

**Expected behavior**
The settings window for the plugin opens up, and OBS Studio continues running

**Logs**
https://gist.github.com/flakywanderer/917ea25f7656e99b7397e560d5a2553b#file-obs-log
I cannot access the settings to enable debug options, as trying to open the settings causes the crash. 

**Version information**
 - OS: Manjaro Linux
 - OBS Version 30.2.0-tytan652-1 (built from [https://aur.archlinux.org/packages/obs-studio-tytan652](https://aur.archlinux.org/packages/obs-studio-tytan652))
 - Plugin Version 1.26.4-1 (built from [https://aur.archlinux.org/packages/obs-advanced-scene-switcher](https://aur.archlinux.org/packages/obs-advanced-scene-switcher))

**Additional context**
The plugin itself loads without error, and the associated dock widget loads and says that advanced scene switcher is active, but none of the macros I have set actually run.

**Comment by WarmUpTill** [comment]
You might be able to get more logs by manually modifying the scene collection json file.

The ‘advanced-scene-switcher’ section should contain an integer value with the name ‘logLevel’.
If you set it to ‘2’ the logs will be more verbose.

But please make sie to back up the JSON file beforehand just in case something goes wrong.

Are you able to provide a back trace fromme the generated core file?
This should narrow down the problem area quite a bit.

Unfortunately I won’t be able to look into the issue for now since I only have rather limited access to my development environment.
So I apologize in advance if it will take a bit to resolve this issue.

**Comment by WarmUpTill** [comment]
I believe this crash was fixed with 223ce0d0a0a076d0e0b051caf627fc354f75581d.
Can you confirm this on your end?

**Comment by flakywanderer** [comment]
Yes, it indeed does fix the crash.

**Comment by WarmUpTill** [comment]
Thank you for the confirmation!
I will try to release a new version containing this fix _soon-ish_.

**Comment by WarmUpTill** [comment]
An official release containing this fix was now published, so I am closing this issue :)
