### ISSUE TITLE
"Process" condition trigger source list empty and failure to detect active processes

### ISSUE THREAD

**Issue by Flynt56** [WarmUpTill/SceneSwitcher#1161]
**Describe the bug**
The "Process" macro condition fails to detect running processes. Manually typing process names into the combo box doesn't help. The "Current foreground process" is always empty.

**To Reproduce**
1. Create a macro
2. Add a condition
3. Select the "Process" trigger
4. Observe it being empty
5. Typing the process name manually doesn't help

**Expected behavior**
A list of all running processes displayed in the dropdown menu. Triggering the macro once the chosen process name is the currently active foreground process.

**Logs**
N/A

**Version information**
 - OS: Nobara Linux 39 (KDE Plasma, Wayland, 6.8.12-200.fsync.fc39.x86_64)
 - OBS Version 30.1.1 (Nobara repository - non-flatpak)
 - Plugin Version 1.26.4

**Additional context**
The "Window" condition is a nice alternative. Unfortunately, some apps display currently opened project names or file names instead of the app's name in the window title.

![01](https://github.com/user-attachments/assets/a8b85c27-77f8-4783-9587-0acf745062f7)

**Comment by WarmUpTill** [comment]
Unfortunately, it is a known limitation that the "focus" part does not function on Wayland based systems.
This functionality relies on X11 being available. (Similar to https://github.com/WarmUpTill/SceneSwitcher/issues/512)

However I would have expected the parsing of /proc/ to work regardless of this limitation.
So, the process selection should not be empty.

Can you please share an OBS log or check yourself, if it contains one of the following log entries:
`libproc2 symbols resolved successfully`
`libprocps symbols resolved successfully!`

If you don't see either of them can you please try to install both of them? (I am not sure which lib was used to build your particular plugin version)

If you do see those log messages, but the process selection is still empty then it _might_ be a permissions issue.

**Comment by Flynt56** [comment]
I already have the `libproc2` library installed via `procps-ng`. Unfortunately, there's no mention of `libproc*` in the latest OBS log file.

[OBS Log File](https://github.com/user-attachments/files/16459157/2024-08-01.17-58-17.txt)

**Comment by WarmUpTill** [comment]
I assume you are using the *.deb file provided in the releases section of this repo?
If so, would it be possible for you to try using this test build?
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/10220515391?pr=1163

The archive containing the binaries / the *.deb file can be found at the bottom of the page and is named `advanced-scene-switcher-1.26.4-33-gd569502f-ubuntu-22.04-x86_64-d569502f9 `.
You will have to be logged into GitHub to be able to download it.

The previous builds in this repo only supported `libproc`, but not `libproc2` since the latter is not available on the Ubuntu 22 GitHub runners.
I have now manually added the `libproc2` package during the build process.

Hopefully this will resolve your issue.

**Comment by Flynt56** [comment]
Still no luck. I use the `.deb` version but manually unpack `lib` into `/usr/lib64/obs-plugins` and `share` into `/usr/share/obs/obs-plugins`. Fedora uses DNF so `.deb` files fail to install. The process selection dropdown remains empty, it's just not visible in the screenshot. I'm ok with closing the issue. I knew Wayland would stop something from working and it's always a surprise.

[2024-08-03 11-51-11.txt](https://github.com/user-attachments/files/16479067/2024-08-03.11-51-11.txt)

![01](https://github.com/user-attachments/assets/2d96c6aa-9dd9-4823-a264-ee2798a7de4a)

**Comment by WarmUpTill** [comment]
Hm ... I am at a loss and I think the only option to get this to work would be to recompile the plugin for your distro or potentially statically linking the lib.

Just to exclude one more possible reason:
The library is named `libproc2.*`, is it not?
It doesn't have the `-ng` in its file name, does it?

**Comment by Flynt56** [comment]
Yup, there are `libproc2.so.0.0.1` and `libproc2.so.0` linked to the former. I've just made another link `libproc2.so` -> `libproc2.so.0` and the list populates but the current foreground process remains empty and doesn't trigger the macro.

Thanks to your question I just randomly did that and it worked! The log file now contains a `16:46:12.450: [adv-ss] libproc2 symbols resolved successfully!`.

**Comment by WarmUpTill** [comment]
Ah that is good to hear!
Just to confirm:
Sorry this apply to the last official release or were you using the test build I shared above?

In case of the latter please be aware that this build might be a bit buggy.
A more stable version can be found here:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/10235662186

**Comment by Flynt56** [comment]
I was using the test build provided above. The build version is visible in my last screenshot.

I'm away on vacation at the moment so I'll reply once I'm able to.

Thanks for the new build!

**Comment by Flynt56** [comment]
Would you like me to try with the latest release (1.27.0) or would you like to close this as the "current foreground process" is a Wayland issue?

**Comment by WarmUpTill** [comment]
Sure, that would be great!

**Comment by Flynt56** [comment]
Yep, the latest version (1.27.0) does list out available processes and the `[adv-ss] libproc2 symbols resolved successfully!` log line is present.

[2024-08-16 11-55-51.txt](https://github.com/user-attachments/files/16635826/2024-08-16.11-55-51.txt)

**Comment by WarmUpTill** [comment]
Thanks for the confirmation! :)

**Comment by HacktheTime** [comment]
I seem to have a similar issue from as far as I can tell. Yet I don't understand this problem to be honest. I had a quick overlook about the log and I am using x11. Maybe the version broke something but same time you seemed to confirm that it worked fine for x11. Using Debian.

![version](https://github.com/user-attachments/assets/8f5297ec-af6e-43f4-8460-fab550111e38)
![firefox not being detected as current](https://github.com/user-attachments/assets/63c45729-32e0-41a0-90ba-7828e1281ba7)

I installed this Plugin via Flatpack for OBS with Flatpak. Yet for some reason, I don't get the Process Ids though. I found this because Intelij is unfortunately not very easy to detect reliably otherwise...

That being said here is the log data from launch.
[log.txt](https://github.com/user-attachments/files/16694122/2024-08-21.16-56-24.txt)

**Comment by WarmUpTill** [comment]
Unfortunately, I don't think you will be able to use the Process condition much, if you are using the flatpak version of the plugin.
The flatpak sandbox does not allow access to `/proc`, which would be required to list all running processes.

>Flatpak [...] may not be suited in some cases:
> * Application needs to read /proc from host or have unfiltered access to processes. This is not allowed as Flatpak has a private proc.
> * [...]
>
>https://docs.flatpak.org/en/latest/introduction.html

**Comment by Flynt56** [comment]
As I mentioned already, Flatpak apps won't show up in the process selection dropdown, even on X11.

Might not be related to the issue, but for JetBrains apps I use their Toolbox app (downloaded off of JetBrains' site) and let it do the rest.

**Comment by Renari** [comment]
I found this because I was trying to get this working as well, modifying the flatpak permissions and giving access to `/proc` did not seem to work. I ended up installing obs native and grabbing the build from the aur and that seems to both list all processes and the focus functionality is working under wayland (although these may be xwayland windows that I'm testing).
