### ISSUE TITLE
When I try to specify a file in the macro match pattern, OBS crashes.

### ISSUE THREAD

**Issue by Ryu-tek** [WarmUpTill/SceneSwitcher#1191]
### Operating System Info

Windows 11

### OBS Studio Version

30.2.3

### Advanced Scene Switcher Version

1.27.2

### OBS Studio Log URL

https://obsproject.com/logs/f03PaVmgJ320WVcv

### OBS Studio Crash Log URL

https://obsproject.com/logs/4appPL7lXXEuvdMZ

### Expected Behavior

It works without any problems

### Current Behavior

When I try to specify a file in the macro match pattern, OBS crashes. Is there a way to fix this?
<img width="752" alt="スクリーンショット 2024-09-01 015035" src="https://github.com/user-attachments/assets/fa9f2269-f2db-4918-a985-445de31be20c">

### Steps to Reproduce

1.specify a file in the macro match pattern
2.OBS crash

**Comment by WarmUpTill** [comment]
I think the issue is happening due to the special character set used in your system.
I have tried to work around this problem and a build with a potential fix will be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/10655878002

I would appreciate if you could give this a try and report back if it resolves the problem or not.
But please make sure to [back up](https://github.com/WarmUpTill/SceneSwitcher/wiki/Saving-and-loading-settings#how-to-create-and-import-a-backup-of-your-settings) your settings just in case anything goes wrong.

**Comment by masugaki** [comment]
I had the same problem and would like to fix it.
However, I don't know how to use the build or how to fix it. Please tell me how to use the build.

**Comment by WarmUpTill** [comment]
Click on the link I shared above.
Scroll down and click on the version of the plugin suitable for your OS.

**Comment by masugaki** [comment]
thank you
