### ISSUE TITLE
Create macro under selected group

### ISSUE THREAD

**Issue by Destroy666x** [WarmUpTill/SceneSwitcher#1196]
### Background

Small QoL change I had on mind for a while, but forgot to post it - just for slightly faster workflow

### Solution

If you have a group selected, pressing the + button should add macro under that group.

Perhaps also add macros below currently selected macros as an addition to that, but groups would already be a good improvement.

### Anything else we should know?

Might look at this myself some day as it seems rather easy on the 1st sight, but can't be sure

**Comment by WarmUpTill** [comment]
Should be implemented with https://github.com/WarmUpTill/SceneSwitcher/pull/1184/commits/d8063755a6a35a338ca652cf837e0a23cd2bcdbf.

The only case I explicitly didn't handle is that of a group itself being selected.
Instead of a new macro being added to this selected group it will be inserted after the last element of the group.
(I didn't want to have to deal with the collapsed / expanded handling of macro groups to support this)

**Comment by Destroy666x** [comment]
Thanks, that seems fine too, definitely much better than it was
