### ISSUE TITLE
Setting up a macro with a certain transition automatically applies that transition to every scene, even disregarding previously set scene transition overrides.

### ISSUE THREAD

**Issue by telopots** [WarmUpTill/SceneSwitcher#1204]
### Operating System Info

Windows 10

### OBS Studio Version

30.2.3

### Advanced Scene Switcher Version

1.27.2

### Plugin settings

AAAGBnicvVRdb9owFP0ryI8VQYTRMvo2KNMqrWtX6B46VZVxboJVY0e2w9oh/vvudYgJ6z60lyEh2cf34/ic62zZmgtrHDv/umWar4Gds4vZ/fX1VWdyO2FdVvLKIehtBbSxXClQ7DznyiFg9HTFdRED3JMsZ88grvXcc+tjnPOmfCe8NNpd5p+MvzAa4mFhTVXGXWbE0xy8l7pAVltmoZDOg40BK+5uKz2pvDe66YvYDRF9hSINX7mPfNkivZLFSuHfX+ZTozMZaC0wI0bYpv4CnvESDPs1UhzhoSeeVPr12V2N4ak4alIz2gcd+ne4hQ7R7h1lvCdCf0oJjCmHdLvMMIBnG+eSYGtCYJIvl6NhOh4kWS5OkyFPIVkO0rdJOhqBOB1wkb8ZYoENWCdJvHTXraeidiw2nJdKenTixriwDzNT0uwM+v1dd79Ox+Pdw77ADLnVRX6fm56NYm6fMhvDPxj/BC8umhLkrEHMfoiqtyFvikLBzc/wQc/Q10GxBu3bUyaMUrx0kMV2WGJa4dyuj4dHtDF29dJRYYmSSRLfCdDkuTKFFHgh9KWynFpfmUzmkuZ4y7xcwyOSct5yqX2Ic0AsA5kNVzSMcdHv4bl/KWm5o3vLOqXlGMKh9RwUiFrgbZPSbR42vujOZLZYzG47341ZE+k6JO2TvOQP5rHeyZxK9U5YUGFhua5NW3BbgA+HUY8WBxSai/+n8qP7Jr1YIUnQfKmo6P4j9A9CBA0OF2ziDhBG35NWByN/7dDZ+Ph39jfHumyp8HXeaS/VQeL6w9i6x54SiQvxNbl6rKUuK/+FW0nXDxiFbdpAY8nnCqoGiSRY2huMegO2+wGZzhRF

### OBS Studio Log URL

https://obsproject.com/logs/FBS3hk3avzSNl87C

### Expected Behavior

I expected the macro to only affect the scenes it is supposed to instead of changing the transitions of every other scene as well.

### Current Behavior

The macro changes all scenes to use the transition specified in the macro settings.

### Steps to Reproduce

1. Setup a macro only affecting 2 scenes.
2. The macro actually changes the transition for all scenes.

**Comment by WarmUpTill** [comment]
You should be able to control this behavior on the General tab.
![image](https://github.com/user-attachments/assets/01ff3e93-1daa-490c-873f-bef16ff6b6f2)
You probably only want to check the "Set transition overrides" box so that the active transition (meaning the one controllable in the "Scene Transitions" dock widget) does not get modified.

If you want more fine grained controls you can use the "Transition" action type to modify the transition settings before the "Switch scene" action.

I hope that solves your issue! :)
If I misunderstood something please let me know.

**Comment by telopots** [comment]
That did it, thank you so much
