### ISSUE TITLE
Directly feeding currently focused window data to a window capture might not be correct due to `:` being in the title/classname

### ISSUE THREAD

**Issue by DVark09** [WarmUpTill/SceneSwitcher#1257]
### Operating System Info

Windows 10

### OBS Studio Version

30.2.3

### Advanced Scene Switcher Version

1.28.0

### Expected Behavior

Expecting to be able to grab the currently active window title and classname and be able to put straight into a window capture to get the currently focused window as a source.

### Current Behavior

If there is a colon (`:`) in the classname/title, the way OBS has the properties in their JSON, it will break and will input the data incorrectly.
Apart from this, there is no way to get the executable name which makes it hard to grab all the processes like this

### Steps to Reproduce

1. Open a window that has a colon (`:`) in the title/classname
2. Trigger a macro that grabs the info
3. Give it to a window capture
4. The window capture will show nothing since the name is broken
![obs64_RE6jJhOPzd](https://github.com/user-attachments/assets/013cf184-07b3-490e-afb9-642cd75ef552)
![obs64_rJAgibDxuM](https://github.com/user-attachments/assets/21b3aecb-701a-4f78-b000-4c51e01d3875)
![obs64_4teAvGJYDU](https://github.com/user-attachments/assets/daae672e-db49-4587-addf-211337e27a09)

**Comment by DVark09** [comment]
Thank you, I didn't know the `process` item holds the correct info that I need for this.
The issue that I opened here is different however. If you check the images, even if I were to use this, the JSON formatting would fail due to the colons in the window titles. OBS needs it to be replaced with `#3A` for the formatting to work properly.
I made a script that gets every foreground window property that replaces colons with `#3A` and that way it works properly

**Comment by WarmUpTill** [comment]
> If you check the images, even if I were to use this, the JSON formatting would fail due to the colons in the window titles.

I think that this assumption might be incorrect.
If it were a JSON formatting issue, using `:` in any other settings value would also fail.
But e.g. changing the text displayed by a text source to `:::` works just fine.

![image](https://github.com/user-attachments/assets/edea8a5b-4e3b-4d75-bab8-7058b8efe2cc)

The issue you are facing originates from how the window capture source handles the values for the window title, class, and process internally:
https://github.com/obsproject/obs-studio/blob/24ea5570876f86710812a7a7303497d708adbec0/libobs/util/windows/window-helpers.c#L8-L44
It uses the `:` character as a separator and replaces it with `#3A` internally.
Looking at the code, a similar issue might also arise for `#` characters.

So, I think instead of changing how the advanced scene switcher handles window titles globally, it would probably make more sense to handle this character replacement for this case via other means.
For example, to expand upon the example available in the wiki you could add two actions of type "Variable", which does the search and replace operation for the affected characters:

![Capture - Copy](https://github.com/user-attachments/assets/412dbfdc-649f-46ae-a633-ed60e973978e)

I will update the example on the wiki accordingly.

**Comment by DVark09** [comment]
Thanks for the feedback!
If any window title has a colon in it it would break functionality on feeding back to a window capture. Perhaps adding an optional checkbox to fix this would be the best?
Changing to ‘:::’ of course works because it is expecting 3 attributes in the same line. My example translates to “Mortyr 2: For ever:Mortyr 2: For ever:Argon.exe” which is incorrect since that would mean we have 5 attributes to fill and therefore obs gets the data incorrectly.
Odd what you are saying, because on my end it worked correctly when I replaced the colons *inside* of the attributes and not the separators themselves. Unfortunately i won’t be able to show it to you until next week.
I disagree that nothing should be changed because the fact that you grab an info from a type of thing (a window) and it can be broken by default when feeding back into the functionality that is tied to said thing (window capture) feels wrong in my opinion. But i have not worked with obs plugins like this previously so i might be wrong
I can live without this since the small script i made fixes this, but maybe someone else has this issue aswell.
Sorry for not replying for a while.

**Comment by WarmUpTill** [comment]
>If any window title has a colon in it it would break functionality on feeding back to a window capture. Perhaps adding an optional checkbox to fix this would be the best?

While I don't have any statistics, I think this is a rather rare use case.
So, the benefit of adding yet another checkbox would be rather low, while potentially confusing a lot of people regarding its intended purpose.

>Changing to ‘:::’ of course works because it is expecting 3 attributes in the same line. My example translates to “Mortyr 2: For ever:Mortyr 2: For ever:Argon.exe” which is incorrect since that would mean we have 5 attributes to fill and therefore obs gets the data incorrectly.

Just to avoid confusion:
The `:::` example I gave in my previous comment was directed towards the statement, that OBS will potentially misinterpret the values passed via the `Source` action type, when modifying settings of source, due to breaking the JSON syntax.
This is not the case as the JSON syntax does not break when changing the `Text` property of a source of type `Text (GDI+)` to `:::`.
This example was not intended to be used for the conversion of window titles for the `Window Capture` specific representation of of the selected window.

The conversion of the `:` and `#` characters should be done via the `Variable` action type, if required.

>I disagree that nothing should be changed because the fact that you grab an info from a type of thing (a window) and it can be broken by default when feeding back into the functionality that is tied to said thing (window capture) feels wrong in my opinion. But i have not worked with obs plugins like this previously so i might be wrong
I can live without this since the small script i made fixes this, but maybe someone else has/will have this issue aswell.

Then we will have to disagree on that point. (Which is completely fine :))
I don't think the window title property made available by the "Window" condition is necessarily directly tied to uses for the `Window Capture` sources and can can serve various other purposes.

If the replacement of characters in the window title property is required for _any_ use case it can be achieved by additional "Variable" actions in a given macro.

>Sorry for not replying for a while.

No worries at all! :)
I really do appreciate you taking the time for reporting a potential problem and feedback is always welcome!

**Comment by DVark09** [comment]
Thanks again for following up. You are probably right with the assumptions and I can understand it.
With this solution and the addition of scripting macro properties, I can consider this resolved since there is a way to resolve my issue.
