### ISSUE TITLE
Trouble Downloading

### ISSUE THREAD

**Issue by Jacobbajki** [WarmUpTill/SceneSwitcher#1260]
### Operating System Info

macOS 14

### OBS Studio Version

30.2.3

### Advanced Scene Switcher Version

1.28.1

### Expected Behavior

From every YouTube video I have seen, most times when the "go to download" button is pressed, the plugin automatically installs. However when I press it, it takes me to the page with all the assets listed below.

### Current Behavior

I am having trouble downloading the plugin since I do not know which asset to install. I've tried all the possible ones and yet when I open the downloaded folders I have no idea which of those files should be inserted into the OBS plugins folder and I was looking to hopefully be pointed in the right direction, thank you.

### Steps to Reproduce

1.
2.
3.
...

**Comment by WarmUpTill** [comment]
I would recommend that you use the installer for MacOS.
It is named `advanced-scene-switcher-1.28.1-macos-universal.pkg` for the latest release.

Once you have downloaded it you will have to "right click" or "control click" on the file and select "open".
Otherwise MacOS will block the execution as shown in gif below.

![Example](https://github.com/user-attachments/assets/1b1b18b0-5b88-4c1d-8b38-b9acecbe7efb)

>From every YouTube video I have seen, most times when the "go to download" button is pressed, the plugin automatically installs.

I don't think there is a way to configure the "go to download" button to automatically run / install files on your computer.
That would be a huge security risk.
I assume the videos you have watched simply omitted the execution of the installer for brevity.

**Comment by Jacobbajki** [comment]
Thank you so much! Everying is working perfectly, appreciate it.
