### ISSUE TITLE
Macro conditions not working as expected

### ISSUE THREAD

**Issue by tatunts** [WarmUpTill/SceneSwitcher#218]
Hello @WarmUpTill !

I think here would be better for us to talk and discuss about the beta builds :)

So this is my problem: having a simple two conditions trigger (if scene and not source is showing) is not working for me. Here are a couple of screenshots:

My idea is to change a text based on that trigger:

![NXz7pxgegb](https://user-images.githubusercontent.com/25224882/120081717-5a258300-c095-11eb-93e2-a57e5c4dc204.png)

This is what happens when I hide this source:

![mtAnZbqOkJ](https://user-images.githubusercontent.com/25224882/120081731-6b6e8f80-c095-11eb-8496-dd73d3fb5665.png)

If I hide the `GSS` source, the text is not changed. This macro works if I take out the first if scene condition.

Not sure if I'm doing something wrong here... As I've asked before, conditions are not very clear for me as how they work together with AND, OR and so on.

I was wondering: what `Ignore entry` does?

Here is the log file as you asked.

[2021-05-29 15-36-06.txt](https://github.com/WarmUpTill/SceneSwitcher/files/6565201/2021-05-29.15-36-06.txt)

Thank you!

**Comment by WarmUpTill** [comment]
> This macro works if I take out the first if scene condition.

This can also be confirmed in the log file:

```
15:45:39.952: [adv-ss] condition scene returned 0
15:45:39.952: [adv-ss] condition source returned 1
15:45:39.952: [adv-ss] Macro Macro 1 returned 0
```

The scene condition is always false (so the top checkmark is not set from the plugins point of view).
Meanwhile the source condition switches between 1 and 0.

Which scene is "Ajustes iniciais" using? (Is it also "Starting soon"?)
That one seems to be reported as being currently active.

Can you maybe export your plugin settings so I can import them on my end to replicate the issue?

Replicating the same setup I am not facing the problem you are having.
Attaching screenshots just in case I made an obvious mistake in my setup: 
![notShowing](https://user-images.githubusercontent.com/19472752/120083930-81e40d80-c0cc-11eb-832b-b3c8a6610401.PNG)
![showing](https://user-images.githubusercontent.com/19472752/120083931-84466780-c0cc-11eb-89a8-bd2180e0f8d0.PNG)

>I was wondering: what Ignore entry does?

The condition is skipped if ignore is specified.
The other conditions (if there are more) are still checked.

**Comment by tatunts** [comment]
Hello!

Yes, `Ajustes iniciais` also has the same scene as trigger but it was disabled, as you can see by the screenshot I've sent, not sure if this is expected or not...

Here is my config backup:

[SS BKP.txt](https://github.com/WarmUpTill/SceneSwitcher/files/6565308/SS.BKP.txt)

Thanks.

**Comment by WarmUpTill** [comment]
These are the settings used for `Macro 1`:

```
      {
         "actions":[
            {
               "action":2,
               "id":"source",
               "settings":"{\"align\":\"left\",\"font\":{\"face\":\"Montserrat\",\"flags\":1,\"size\":80,\"style\":\"Bold\"},\"outline\":true,\"outline_color\":4278190080,\"outline_size\":1,\"text\":\"MUDAR TEXTO\",\"valign\":\"center\",\"vertical\":false}",
               "source":"Game title"
            }
         ],
         "conditions":[
            {
               "displayUnit":0,
               "id":"scene",
               "logic":0,
               "scene":"",
               "seconds":0.0,
               "type":0
            },
            {
               "condition":1,
               "id":"source",
               "logic":103,
               "settings":"",
               "source":"Data e hora"
            }
         ],
         "name":"Macro 1",
         "pause":false,
         "pauseHotkey":[
            
         ],
         "unpauseHotkey":[
            
         ]
      }
```

The value causing your issues is `"scene":"",`.
It means no scene is currently selected for this entry, but in your screenshot it is visible that the current selection shows a scene being selected.

I have a hunch what could be causing this:
Sorting the scene selection alphabetically.

The reason for this is that the selection QComboBoxes always start out by selecting the very first entry that was added to them.
In the past that used to be the `--- select ... ---` entries, representing "no selection was made yet".
But now the `--- select ... ---` entries is added at the very end after all existing entries have been sorted alphabetically.
This is done to avoid the issue of someone having scenes names beginning with "--- s1" being sorted incorrectly.
This means that which every scene was added first to the list now represents the empty selection instead of the `--- select ... ---`.
I assume in your case it was the `Starting soon` scene.

I have submitted a fix for this behaviour with https://github.com/WarmUpTill/SceneSwitcher/pull/219/commits/bd378d6086531ed05e967c5c8878943b78af7948.

A build will be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/889035697

Let me know if that resolves the issue.

**Comment by tatunts** [comment]
Problem is fixed :) Thanks a lot!
