### ISSUE TITLE
Be able to choose if macro actions are constant/forced or not.

### ISSUE THREAD

**Issue by nacalai** [WarmUpTill/SceneSwitcher#290]
Sorry for the title, I couldn't find a better way to describe it. I don't know if this perhaps contradicts how the plugin is supposed to work, or if it is a simple feature to implement.

As it is now, if I for example have a `if scene active is Cam1 - then unmute Mic 1`, the Mic 1 will be forced unmuted no matter what. I can not mute it again if I for some reason would want that as long as Cam1 scene is active.

It would be neat to be able to choose the trigger behaviour. Do the action once then release, or constant.

If this already is a feature, then my apologies, but I have not been able to find such a thing. This can of course be done with using macros to control other macros on/off but that will just be a big mess if I want a lot of them.

**Comment by WarmUpTill** [comment]
I added the option to only trigger the macro condition "scene" when the scene was changed recently with the linked PR:
![OnChange](https://user-images.githubusercontent.com/19472752/131893235-bb99e685-9c58-42eb-a15c-7366590bc07b.PNG)
A build with this change will be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/1195215904
Let me know if I understood your request correctly and this works as expected! :)

**Comment by WarmUpTill** [comment]
Maybe to add to this topic:
You also have to option to specify time restrictions to most condition types by clicking the small clock symbol, which is also visible in the top right of the above screenshot.

So for example you can configure something like:
If current scene is X _**for at most Y seconds**_ mute Desktop Audio.

If you choose a low value for Y it should result in pretty much the same behavior introduced with the linked PR.
(Which is why on second thought I might now merge these changes)

**Comment by nacalai** [comment]
Aha, I did not know I could do it that way with the clock. The "for at most" just confused us so we never used it. I guess it does make sense now, and it would not really be necessary to add the checkbox, but, there might be other people like me thinking they're stuck with it being forced on constantly, so maybe the checkbox can come in handy.
