### ISSUE TITLE
Explorer.exe bug

### ISSUE THREAD

**Issue by DamsDev1** [WarmUpTill/SceneSwitcher#31]
I don't know if it's possible to fix this, but the program that manages Windows windows is called Explorer.exe . But the Windows file manager is exactly the same program. Is it possible to make the plugin only detect when it is the file explorer and not any window?

**Comment by WarmUpTill** [comment]
I am afraid I can't think of a good solution to this problem, because, as you already mentioned, the "explorer.exe" process is also running even if no file explorer window is opened. 
(Unless you manually kill the process of course - but this leaves you without a taskbar)

Maybe it could be possible to match Window Titles instead for your use case?
