### ISSUE TITLE
Daily Stream Trigger

### ISSUE THREAD

**Issue by justincaaase** [WarmUpTill/SceneSwitcher#438]
First, I apologize if this is an issue with me and not the plugin.

I have a stream that's always ready to go, and just needs to start/stop streaming every weekday at the given times. I've set up a macro to do just that. The stream start macro is below. I've got it set on "simple" settings because I can see that the "advanced" settings include the actual date rather than the day of the week.

```
[If] [Date] on [Monday] at [20:00:00]
[If] [Date] on [Tuesday] at [20:00:00]
...

[Streaming] [Start streaming]
```

This worked great for the first week, then on Monday of the second week the stream didn't trigger at the scheduled time. The only problem I suspect is that the macro trigger is holding on to a specific date (e.g. 3/21/22, 3/22/22, etc.) and so it didn't trigger of Monday this week.

**Comment by WarmUpTill** [comment]
Would you mind exporting your settings to a file and sharing it here? (Can be done on the General tab)

This will make it easier for me to replicate the setup on my end and check for potential issues.

**Comment by justincaaase** [comment]
Sure! Thanks for your help.

[adv-ss-Untitled-2022.04.01.12.17.06.txt](https://github.com/WarmUpTill/SceneSwitcher/files/8399761/adv-ss-Untitled-2022.04.01.12.17.06.txt)

**Comment by WarmUpTill** [comment]
I have a theory what might have happened:

The previous implementation of this condition checked whether the selected date falls into the range of "now" to ("now" + "switcher interval").
This will work in most cases, but if things align just right the selected date might fall exactly the range of ("now" + "switcher interval" + "some short amount of time before the next date check is performed")

To resolve this problem I adjusted the date condition to take into account when the last time was it had performed a date check instead of just the fixed value of "switcher interval".

A build with this change should be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/2081979137

**Comment by justincaaase** [comment]
Thanks so much. I'll give the new build a go and report back next week (after the next scheduled weekday stream(s).

**Comment by WarmUpTill** [comment]
I merged the changes already as I plan to release an update soon and it makes sense to include them.
Please report back if you should encounter any issues - thank you!

**Comment by WarmUpTill** [comment]
I will close this for now.
If you did encounter any problems let me know and I will reopen the issue. :)
