### ISSUE TITLE
Feature: Refresh browser source

### ISSUE THREAD

**Issue by nacalai** [WarmUpTill/SceneSwitcher#488]
I vaguely remember seeing refresh browser source action, but I've must've been wrong. This would be a nice feature to have for a current project I have.

**Comment by WarmUpTill** [comment]
I *think* you might be able to achieve what you are looking for by changing the settings of the browser source by using the "Source" action type and just reapplying the current settings.

To make this less error prone I added the option to just reapply the current settings as a different option for the "Source" action type.
![Refresh](https://user-images.githubusercontent.com/19472752/177014859-5677e689-57ab-46dc-b42a-dfde8affba85.PNG)

You can download a build with this change in the linked PR.
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/2602347975

Let me know if that works as expected.

Also, apparently the browser source is registering an OBS hotkey to trigger a refresh of the browser source according to https://github.com/obsproject/obs-browser/commit/f5c50da4d1b79139cbaf4c89739e6b15fbfafcfc, but I couldn't find it for some reason in my OBS test environment.

**Comment by nacalai** [comment]
Thanks, I already tried setting the same settings, but didn't work. I am guessing this option won't make any difference, but I'll try.

**Comment by WarmUpTill** [comment]
Hm ok, that is unfortunate.
Seems like the browser content is only refreshed if the settings change.

> Can't you just emulate hitting the refresh button or call the event or something?

In theory I could try to cast the source to the more specific browser source type and call the Refresh function, but then I would have to rely on the browser source structure to remain stable or otherwise things would break whenever there is a change on the browser plugin side.

The only workaround I can think of at the moment is to toggle the visibility of the Browser source and enable "Refresh browser source when scene becomes active".

If the hotkey previously mentioned refresh hotkey of the browser source would work you could also use the Hotkey action to trigger the refresh, but for some reason I cannot find any such hotkey in the OBS settings.

**Comment by WarmUpTill** [comment]
Seems like there is a way to simulate a button press that does not rely on known the internals of the source type:
https://github.com/obsproject/obs-websocket/pull/666/files

I have updated the PR to contain this method of refreshing browser sources.
A build should be available here in a few:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/2742418257

Let me know if that also works on your end!
