### ISSUE TITLE
Plugin failed to load on OBS 28

### ISSUE THREAD

**Issue by brownsugar** [WarmUpTill/SceneSwitcher#497]
**Describe the bug**
After I upgrade OBS to 28.0.0 beta, this plugin cannot load properly.

**To Reproduce**
1. Download OBS 28 beta from [official release](https://github.com/obsproject/obs-studio/releases/tag/28.0.0-beta1)
2. Overwrite files
3. Launch OBS Studio
4. Get the error: The following OBS plugins failed to load: **advanced-scene-switcher**
![image](https://user-images.githubusercontent.com/2935980/183100076-aec68ec5-3f90-4f50-8a8c-131800ac58a7.png)

**Expected behavior**
The plugin should loaded normally as in OBS 27.

**Logs**
https://obsproject.com/logs/89xEuYx5l_0htlU9

**Version information**
 - OS: Windows 11 21H2 22000.832
 - OBS Version: 28.0.0-beta1
 - Plugin Version: 1.17.7

**Comment by WarmUpTill** [comment]
Thanks for reporting the issue.
Unfortunately that is to be expected due to a version change in the QT libs that are shipped with OBS 28.

I am already working on implementing the necessary changes to support this new version.
I will let you know once  test version is available.

I will however not release this officially until OBS 28 leaves its beta phase, as it would mean that the plugin no longer works on OBS 27.

**Comment by WarmUpTill** [comment]
First builds for various platforms, which support OBS 28, are available here:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/2853883417

I would appreciate if you could give this a try and report back if you face any issues.

And sorry for not getting back to you sooner.
Setting the automated builds up turned out to be a bit trickier than I thought.
