### ISSUE TITLE
Feature Request: MIDI Condition Type

### ISSUE THREAD

**Issue by jernanigans** [WarmUpTill/SceneSwitcher#520]
**Is your feature request related to a problem? Please describe.**
I think it would be really useful to a lot of musician streamers if MIDI input could be used as a trigger condition.  Here is a little more background:

I am a pianist whose streams consist of playing a digital keyboard, and some talking in between songs.  I am trying to figure out how to cycle through one set of scenes when I am talking, and a different set of scenes when I am playing keyboard.

I think it would be useful to be able to detect activity on a selectable MIDI device, and use that input to perform various actions (like scene selecton)

**Describe the solution you'd like**
The solution I would like is to be able to set up a condition based on MIDI activity:

If MIDI [Duration Modifier(s)]:

_Dropdown: MIDI Device_
- All MIDI devices
- List of all connected MIDI input devices so user can pick a specific one for the trigger

_Dropdown: MIDI Channel_
- All MIDI channels
- List of 1 - 16 to allow the user to pick one channel for the trigger

_Dropdown: MIDI note_
- Any MIDI notes
- List of all possible MIDI notes to allow the user to pick a specific note for the trigger

_Button: Listen_
- A button that has OBS listen for MIDI input from the selected device / channel, so the user can press a key on their MIDI controller to populate the MIDI note

**Describe alternatives you've considered**
An alternative solution I've considered is looking into this using OBS plugin, but it is not compatible with OBS 28.0.
https://github.com/cpyarger/obs-midi

Another alternative solution would be to use something like Midikey2Key to map MIDI to a keyboard shortcut, and then have Advanced Scene Switcher listen for that keyboard - but I think it would be nicer to have it built in natively.
https://midikey2key.de/

**Additional context**

**Comment by WarmUpTill** [comment]
Thanks for the suggestion! :)

Just a question as I am not familiar with MIDI sources at all.
What exactly is meant by "MIDI activity"?
Does "active" stand for an audio source is currently playing something?

Background for my question:
How would this differ from the audio condition type?

**Comment by HSFlik** [comment]
NP, thank you for being open to this concept!

MIDI is a digital standard that was developed by Roland + Dave Smith as a way to standardize the way musical instruments communicate with computers, and with other MIDI compatible notes.

It differs from the audio condition type in that while audio is a digitized waveform, MIDI data is made up of digital events, called MIDI messages.  MIDI is not audio, but rather specific digital commands.

![image](https://user-images.githubusercontent.com/3045423/188547633-35a154a7-ae83-45e4-beee-45cb5e252cb4.png)

A keyboard like the one above is called a MIDI controller.  This one in particular does not have the ability to create audio that can be sent to a speaker.  Instead, it sends MIDI messages to a device that is capable of creating audio - like a synthesizer or a computer.

When the user presses a key on that keyboard, it sends a "Note Down" event containing the value of that note (like say, Middle C) with a specific velocity (how hard the user pressed the key), and then when the user releases the key, it sends a "Note Up" event to the computer / synthesizer.

The computer / synthesizer will take this message and do whatever it wants with it, most commonly turn it to audio somehow.

There are many different kinds of MIDI messages -/ events, like note up / note down, and other ones for buttons and pedals on keyboards or other.

Here is a brief intro to MIDI from a music store:
https://www.sweetwater.com/insync/midi-essential-guide/

MIDI is an essential component of digital music production - people who use Digital Audio Workstations (DAW), like REAPER, Logic, FL Studio, Ableton, Pro Tools, etc use MIDI controllers to play back instruments they have on their computer.

The reason this would be useful for me, is that I would be able to make a trigger based on whether I was playing the keyboard or not.

Consider that I want to automate different scenes depending on if I am speaking, or playing keyboard.

A common setup for music streamers is to use a mixer, or audio interface to plug their instruments into.  This mixer or audio interface will be the single audio device recognized by the computer.  I can plug both a keyboard and microphone into this mixer, and the computer will not be able to differentiate between the keyboard or microphone - both separate audio signals are combined to one by the time it gets to the computer.  Furthermore, the microphone will pick up on the physical noise of my fingers pressing down the keys on the keyboard if I am wearing headphones to try to isolate the sound.

However, my keyboard (and just about every keyboard) also has the capability to send MIDI data at the same time - meaning that whenever I press the keys, the computer receives a MIDI message which is completely independent of the audio picked up from the mixer.

Here is a VOD of my stream so you can get an idea of the flow:
https://www.youtube.com/watch?v=v4JLjoFddRs

If Advanced Scene Switcher supported MIDI, streamers could use MIDI controllers to trigger different actions depending on which note or button they press.  Similarly, if OBS detected a lot of MIDI messages from the keyboard coming through at once, I could trigger some up-close hand camera angles.  If there were not a lot of MIDI messages coming from the keyboard, then I could trigger some wider shots, or up close face shots since I will probably be talking to the viewers.

I do understand that this would be a huge undertaking and this is a very narrow subset of OBS users, musicians that is - but I figure it's worth bringing up since I know a lot of musician streamers that could potentially benefit from this.

**Comment by WarmUpTill** [comment]
Thank you very much for the detailed explanation and examples!
I will look into it, but I cannot promise that I will get anything working soon, as testing will be rather difficult.

**Comment by warpeggio** [comment]
I love this idea and i think it would be useful to the music streaming community. @WarmUpTill if you'd like, i can provide you some loaner hardware to play with at no cost as a service to your project and the community.

**Comment by nacalai** [comment]
Can this plugin possibly give some insight? It is also compatible with v28 and does appearantly have actions. @HSFlik https://github.com/nhielost/obs-midi-mg

**Comment by mishakim** [comment]
To add an additional sub-feature request, it would be nice to also send MIDI commands in the Action side of a macro, not just listen for them on the Conditions side. That is, when the trigger happens, like switching to a given scene, then send off the specified MIDI command. In my case, I'd like to send some commands to my DAW to automatically change the audio mix when switching to certain scenes. MIDI is the only mechanism it has for doing that. I'm using obs-midi-mg for MIDI input, but it also doesn't have this ability.

**Comment by WarmUpTill** [comment]
I finally got around to implementing an initial basic version of this functionality.
(I apologize that it took so long!)

![MidiCond](https://user-images.githubusercontent.com/19472752/232167285-5793947b-44a2-45b3-b69c-75dfd6b329ee.PNG)

For now only the checks for the following fields of the midi message are supported:
- channel
- note
- value

A build containing this new condition type should be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/4704444201

I would appreciate if someone with a real midi device could give this a try and report back, if this basic implementation works as expected, as at the moment I am only testing this implementation with virtual midi devices.

**Comment by WarmUpTill** [comment]
I now implemented the support for specifying the desired message type.
The requested button to listen for input to make the message selection easier has also been added.

I also added the "MIDI" action type as suggested.

![Midi](https://user-images.githubusercontent.com/19472752/232237609-bf3d76f4-c5be-4f65-b0d3-3543b43efd3f.PNG)

A build with these changes should be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/4708704846?pr=713

Feedback would be much appreciated! :)

**Comment by mishakim** [comment]
Trying it out, setting transition to certain scenes to trigger Midi control commands. So far, UI seems to be what I expect, and listening to commands to capture their settings works, but the Midi actions aren't doing anything. Using MIDI Monitor app to sniff, it doesn't see any commands coming out of OBS.

I don't have any physical MIDI hardware - I'm using a StreamDeck to send Midi commands, and OBS and my DAW software (Sound Desk) are listening for them. I'm also using obs-midi-mg to listen to commands and trigger hotkeys -- I could switch to using Scene Switcher only if that's interfering (once it's stable). Running an M1 Mac with the Arm64 version of everything, Ventura 13.2.1, OBS 29.0.2

OBS crashed when I tried to add Midi action to a second macro (first got created OK). Log: https://obsproject.com/logs/VzOOOlT4x5iCvUOU

[posting what I have for now, will do more thorough investigation in a bit]

**Comment by mishakim** [comment]
Some more testing:
Receiving commands works - I press MIDI buttons on StreamDeck, OBS responds as configured.
Sending commands does not work - Macros that have MIDI actions do not send them. If they have other actions, those work, but the MIDI actions do not. MIDI Monitor does not show any activity when the macro should be sending commands.

I have had the crash repeat - when adding a second MIDI action to a macro. But I can't reliably reproduce it, adding a second MIDI action does work sometimes.

Log: https://obsproject.com/logs/Gd7H7fVpB27uvZ3L

**Comment by WarmUpTill** [comment]
Thanks a lot for the tests!
I really do appreciate it! :)

Regarding the crashes:
Do you still have the crash report as well? (Not sure if / where they are stored on MacOS)
I _think_ these crashes might happen due to unhandled driver errors when opening devices.
I added additional error handling for these cases.
A new build should be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/4714995361?pr=713

Regarding the actions not working:
What type of message were you trying to send? Do you still have the OBS log files of this happening?
I was only able to test simple "Note on" and "Note off" messages, so maybe special handling for those other message types is required.

**Comment by mishakim** [comment]
I didn't get the MacOS crash reports (I assume I could have when it told me OBS crashed - I just didn't occur to me to do so; I'll grab them if it happens again)

Testing with the new build on my personal machine instead of the production machine, it's working -- no crashes so far, and the MIDI actions are sending commands when my macros run. I'll have to head back to church to try on the production machine where I was having problems. Might be a few days.

The message types I'm sending are CC commands, I'm using a few different messages for gain control and mute toggle in Sound Desk. I'm not totally clear on MIDI terminology, but Scene Switcher is calling message number "notes," which is fine with me, but I think it has a different name when its a CC command.

**Comment by mishakim** [comment]
I've done some more testing. I think my remaining problem is with SoundDesk (my DAW), and that SceneSwitcher is working in general, just not for me. 
TL/DR: Stream Deck-generated virtual ports don't route messages from OBS to other apps, and SoundDeck isn't usable with a macOS-generated virtual port, but it does look like OBS is working correctly with that port. 

Here's what I'm seeing:
I'm using a Stream Deck to send MIDI commands to SoundDesk. I want OBS to also send MIDI commands to SoundDesk. For troubleshooting, I'm using two apps, MIDI Monitor and MIDI Tools, to monitor the MIDI traffic and simulate a DAW. 

I'm using a virtual MIDI port provided by the MIDI Button plugin in Stream Deck, the port is named V-MIDI.
When Stream Deck sends a command, MIDI Monitor shows a message "from V-MIDI "; StreamDeck and MIDI Tools respond correctly.
When something is adjusted directly in SoundDeck or MIDI Tools, MIDI Monitor shows a "to V-MIDI" message;
When an OBS macro sends a MIDI command, MIDI Monitor shows a "to V-MIDI" message, and SoundDeck and MIDI Tools do not respond.
So it seems like the problem with this setup is that SoundDesk is only listening to commands coming "from" the virtual port (i.e., from Stream Deck), and not commands that OBS is injecting to the same MIDI port -- they are going from OBS "to" the virtual port, which doesn't get them into SoundDesk.

Trying a different configuration, I set up a virtual MIDI port in the macOS built-in Audio MIDI Setup app. With SoundDesk not running, it looks like this should work - both Stream Deck and OBS produce both a "from" and a "to" message for that port on every action. Seems like that was the missing link, and MIDI Tools responds to both the Stream Deck and OBS correctly, and it also sends both "from" and "to" message on each action. But when SoundDeck is running and set to use that virtual MIDI port, (a) it floods the MIDI port with spurious messages, and (b) it echos incoming messages 1000s of times (or is causing other devices to flood the port), rendering itself unusable and eventually crashing the other MIDI apps. 

So, I need to either find a way to make SoundDesk work with the native virtual port, or find a different DAW that will do what I want.

**Comment by WarmUpTill** [comment]
@mishakim Thanks a lot for your extensive tests!
If should find any indication that the plugin is somehow related to the issues you are facing please to let me know! :)

I will probably go ahead with the merge of these changes to the master branch in the coming days as the current state of this implementation should hopefully be useful in some scenarios.
