### ISSUE TITLE
"any media source" needs obs restart

### ISSUE THREAD

**Issue by michael-dm** [WarmUpTill/SceneSwitcher#564]
When using "any media source" in media macro, if a media is added after the macro was created it won't work until next OBS restart.

**Comment by WarmUpTill** [comment]
I improved the option to match multiple media sources in one condition with the linked PR.
The source list will now be updated every scene change instead of only when changing a setting in the condition.
Additionally I added the support for "placeholder" scenes, like "Current scene", "Previous scene", ... .

A build with these changes should become available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/3281376208
