### ISSUE TITLE
Default transition is changed by Macro

### ISSUE THREAD

**Issue by elementsevenx** [WarmUpTill/SceneSwitcher#576]
When setting a macro with a certain transition - it will change the default transition.

**Steps to reproduce**
Create a macro
Choose a transition between scenes
Complete conditions for macro to trigger
See that default transition has changed to the transition used in macro

**Expected results**
Macro triggers and plays
Default transition remains unchanged

This issue is particularly annoying as I have some default transitions I like to have set by OBS for all other scenes that do not require a specific transition that I set in Transition table. So, every time I use a macro with SceneSwitcher, it'll switch that out and sometimes I forget this, and the transition I use between these universal scenes ends up being the wrong one.

I'd like to request if possible, that the macro does not change this and my default transition remains the same so I don't have to keep switching the transition each time I use a macro.

**Comment by WarmUpTill** [comment]
Sorry about the late reply.
I somehow completely missed your request.

There is actually already a way to do this but it is a hidden.

First you will have to enable the old legacy tabs again by unchecking the following option on the General tab:
![Gernal](https://user-images.githubusercontent.com/19472752/200110831-02c6dce9-4f20-4c91-be41-e8d9fdebcb55.PNG)

Next on the Transition tab uncheck "Set active transition" and leave "Set transition overrides" enabled.
![TransitionTab](https://user-images.githubusercontent.com/19472752/200185545-ee15f397-8914-4726-8bd9-b2f039e0d4d7.PNG)

This will now only change transitions using the transition override mechanism instead of changing the active transition (and if possible restore it afterwards).

I will make sure to move this option to the General tab instead so it is more accessible.

**Comment by elementsevenx** [comment]
Oh, I didn't think to look in hidden settings. Thanks for the heads up and yes it would be perfect to have it exposed in General. This did fix my issue so thank you!
