### ISSUE TITLE
Very inconsistent and problematic triggering

### ISSUE THREAD

**Issue by vertigo220** [WarmUpTill/SceneSwitcher#610]
**Describe the bug**
I'm using this for motion detection to trigger recording, but it's proven to be inconsistent to the point I can't use it at all. I have it set to start recording if the video changes with pattern matching at a threshold of 0.9 and to stop recording if there's no change for at least 60 seconds with the same threshold. Unfortunately, I've had it act in a variety of ways other than this. Initially, it worked fine, but then when I tried again it kept triggering recording. It took me a while to figure out why, since the phone (using with DroidCam OBS to use the phone's camera as a video source) was lying with the camera down on a table, but then I saw it was very slightly raised and there were extremely faint fluctuations in the lighting of the image that were triggering it. With a threshold of 0.9, I find it very surprising this small amount of change triggered it. Worse still, I later set the phone up and set an area to use for monitoring for change, and despite being so sensitive earlier, when it went from a dark room to the light being turned on, it wasn't triggered. Then later, without the light on and with no significant change occurring, it kept rapidly switching between starting and stopping recording, which it shouldn't have done at all since it's supposed to wait 60 seconds before stopping.

**To Reproduce**
See above

**Expected behavior**
It should trigger when expected, and not when not expected. It should not trigger when there's almost no change and trigger when there is change, based on the threshold, vs currently where it's triggering with almost no change and not triggering with large changes.

**Logs**
No verbose logs, though it's enabled now, so I'll try to post them when it happens.
 
[adv-ss-Untitled-2022.11.30.18.45.30.txt](https://github.com/WarmUpTill/SceneSwitcher/files/10128139/adv-ss-Untitled-2022.11.30.18.45.30.txt)

**Version information**
 - OS: Windows 10
 - OBS Version 28.1.2
 - Plugin Version 1.19.2

**Additional context**
A bit of a separate issue, and not really a bug so much as what seems like an oversight, but when set to start recording on change, it kept starting it even with no video feed, so I had to add another condition to prevent that (not if source has not output). That should be implied and automatic if looking for change, since there can be no change from null to null.

**Comment by WarmUpTill** [comment]
I think it might make sense to add a duration modifier to your video condition in the "Motion Recording (Start)" macro, so that minimal changes will not immediately trigger the action to start a recording.

For example something similar to this:

![StartRecord](https://user-images.githubusercontent.com/19472752/205447636-5d27588f-90c4-4fae-b69f-dc083911f204.PNG)

Also your "Motion Recording (Stop)" and "Motion Recording (Start)" macros can (and likely have according to your description) both be true at the same time.

---

I would recommend to instead just reference the conditions of the "Motion Recording (Start)" macro in "Motion Recording (Stop)":

![StopRecord](https://user-images.githubusercontent.com/19472752/205447749-432caf07-2256-469b-be24-4bbcf00743bc.PNG)

This also has the upside of being less resource intensive and error prone.

---

>Worse still, I later set the phone up and set an area to use for monitoring for change, and despite being so sensitive earlier, when it went from a dark room to the light being turned on

Can you provide example images?
Maybe I can find a different algorithm which handles those situations in a better way.
