### ISSUE TITLE
OBS Settings as actions/feedbacks

### ISSUE THREAD

**Issue by nacalai** [WarmUpTill/SceneSwitcher#724]
Not sure if even possible to implement, but being able to read and write the OBS settings would in many cases come in handy. For example, for our very specific use case, stream keyframe **must** be on 2, else the stream will become corrupt. So, having a `if keyframe != 2, do alert notification` would be nice for us.

If it's not possible, then alternatively add a "is not" to the profile action. So, `if profile is not our standard profile, then do this`..etc.

**Comment by WarmUpTill** [comment]
Thanks for the suggestion!

Checking / setting values of the profile config should be possible.
I would however prefer to add those action / conditions to already existing action types instead of introduction a generic "profile settings" action / condition (if applicable).

Sorry to have to ask this, but can you show me a screenshot of which setting you are referring to exactly?
Just to make sure I am looking at the correct values :)

>If it's not possible, then alternatively add a "is not" to the profile action. So, if profile is not our standard profile, then do this..etc.

That should already be possible, should it not?
You can simply use the "If not" logic selection in combination with the "Profile" condition type to achieve this.
(I apologize if I am simply misunderstanding something)

**Comment by nacalai** [comment]
Right, I was totally blind and didn't see the dropdown menu where I can choose "if not". Nevermind that! 


On the topic of the settings, I guess it could be laid under the existing "Profile" indeed. But perhaps it's not obvious enough if people are looking for something along the lines of settings, obs settings, etc. But, I guess it should be fine just putting it under profile.

The mentioned setting would be this one: 
![image](https://user-images.githubusercontent.com/4357694/234383014-4a83ef88-8660-4ca0-b184-8dbfb26ca9b7.png)

**Comment by WarmUpTill** [comment]
A build with the option to check for and set the keyframe interval will be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/4806502810

I choose to add these settings to the "Streaming" condition and action type as these settings are specific to this output if I am not mistaken.

![Keyframe](https://user-images.githubusercontent.com/19472752/234513450-7339d800-8b5f-4828-82ca-d079bd4b4546.PNG)

I would appreciate if you could give this a try! :)
Especially the action to set the keyframe interval, as I am not sure if it is actually applied correctly or not when starting to stream.

**Comment by nacalai** [comment]
Works perfectly. Thank you very much! Quick as always. Perhaps add the rest of the settings in the future? :)

**Comment by WarmUpTill** [comment]
Thanks for the quick test! :)

>Perhaps add the rest of the settings in the future?
I will add them as they get requested - too little time for too much work to do :D
