### ISSUE TITLE
"Scene Item Visibility" works with a delay if it set to SHOW

### ISSUE THREAD

**Issue by JFMugen** [WarmUpTill/SceneSwitcher#807]
**Describe the bug**
I created a macro that makes game window visible and start replay buffer when I focus on game. The issue is, while "Hiding game window" works instantly, "Showing" it adds a delay as long as my "Check Conditions" time. So if I put it to 5 second, game window becomes active 5 seconds after the replay buffer starts. Replay buffer is under Show Window as well in priority order so it is weird that replay buffer can even start before "Show Window". 

**To Reproduce**
Create a macro like this and save a replay

![image](https://github.com/WarmUpTill/SceneSwitcher/assets/61559703/371f604d-74ac-43b9-a27e-50144ec30d97)

(You can make "Check Conditions Every.." time long (3-5 sec) to make it easier to see the issue but it is still happening in default 300ms as well)

**Expected behavior**
Windows become active before replay buffer starts. 

**Logs**

Log -> https://obsproject.com/logs/zPkdcO0K8wbYu93h

Settings -> [adv-ss-Untitled-2023.08.01.14.18.10.txt](https://github.com/WarmUpTill/SceneSwitcher/files/12228436/adv-ss-Untitled-2023.08.01.14.18.10.txt)

**Version information**
 - OS: [e.g. Windows 10]
 - OBS Version [e.g. 29.1.3]
 - Plugin Version [e.g. 1.22.1]

**Comment by JFMugen** [comment]
ps. out of topic but I am curious, performance impact between making "Check Conditions" 300ms and 5000+ms is negligible? I won't use OBS most of the day but I will keep it in background, I always forget to open otherwise :/

**Comment by WarmUpTill** [comment]
Unfortunately the log does not contain verbose logs so I cannot say with certainty what is going on, but I assume the following is happening:

Let's assume you start with the PARAGON window being in focus already.

If you switch to a different window only the "Replay Buffer OFF" macro's condition will be true as a window with the name "PARAGON" exists and the focus window changed.
The conditions of "Replay Buffer ON" do not match, because even though a window with the name "PARAGON" exists it is *not* in focus.
Thus only the actions of "Replay Buffer OFF" are executed.

Now if you switch back to the window with the name "PARAGON" the conditions of "Replay Buffer ON" are true, as the window with the name "PARAGON" still exists and now is in focus.
However, also the condition of macro "Replay Buffer OFF" are true as window with the name "PARAGON" exists and the focus window changed (back to "PARAGON").
Now the actions of _both_ "Replay Buffer ON" _and_ "Replay Buffer OFF" will be executed.
As the "Replay Buffer ON" macro is listed above "Replay Buffer OFF" its actions will be executed first. (Which results in the actions of "Replay Buffer ON" being pretty much undone immediately)

Now in the only in the _next_ check interval interval only the conditions of "Replay Buffer ON" are true as the focus window has not changed and _only_ its actions will be executed, which leads to the observed effect of the "Replay Buffer ON" macro's action being executed with a delay.

---

I would recommend having a look at this wiki entry and enabling the visual guides to make it more clear when which macro is being executed.

https://github.com/WarmUpTill/SceneSwitcher/wiki/Troubleshooting#visual-indicators-of-macro-activity-and-status

---

To resolve the particular issue you are facing I would recommend to adjust the conditions of either macro to be the exact inverse of one another using the "Macro" condition.
For example:

![Capture](https://github.com/WarmUpTill/SceneSwitcher/assets/19472752/1d0732ae-ea55-455f-bd28-b872a2c103dc)

Hope that helps!
Let me know if you have any questions! :)

**Comment by JFMugen** [comment]
> Let's assume...

Looks like it is just like you assumed, and your suggestion worked perfectly. Thank you :)
