### ISSUE TITLE
Macro trigger / event editor gets confused and results in duplicated elements.

### ISSUE THREAD

**Issue by KopiasCsaba** [WarmUpTill/SceneSwitcher#841]
**Describe the bug**
This is hard to reproduce sadly:( But let me explain what I did and maybe you'll have an idea what might happened.

So I was editing back and forth a macro, and on 2 or 3 occasions, some of the events or triggers got duplicated, usually multiple times. So I'm guessing something is messing up the internal state, or some race condition happens.

Sometimes it only happens after you close the window and open it back, and then realize why do you have the same thing 4 times.

**To Reproduce**
Just rigorously try to edit triggers and events, and it'll happen. 

**Version information**
 - OS: Windows 10
 - OBS Version 29.1.3
 - Plugin Version 1.23.1

**Comment by WarmUpTill** [comment]
Does the issue heal itself or do the duplicate actions / conditions get removed if you switch to a different macro and back to the problem macro?

The code for handling the displaying of macro actions / conditions has not changed in a _very_ long time.
As this is the first time I have heard about such an issue, could it maybe be the case that you accidentally pressed the condition "+" button instead of the one for the actions or vice versa?
In that case a copy of the last action / condition in the list would be inserted.

Regardless I will keep a look out for any potential issues in that area.

**Comment by KopiasCsaba** [comment]
I needed to delete the conditions/actions. Very well could be a user error, I'll watch more carefully next time and let you know if it happens again:)
