### ISSUE TITLE
[Feature request] Cut/copy actions/conditions to other macros

### ISSUE THREAD

**Issue by Destroy666x** [WarmUpTill/SceneSwitcher#859]
**Is your feature request related to a problem? Please describe.**
This would make setting up easier when moving stuff when refactoring macros or creating a bunch of very similar ones.

**Describe the solution you'd like**
Add a way to cut/copy -> paste actions and conditions to right click context menu. A bonus would be some kind of multiselect with Ctrl + click or checkboxes to cut/copy more at the same time.

**Describe alternatives you've considered**
Maybe possible with some config file direct changes, but not sure. And doing it in interface is ofc always more comfortable and less error-prone.

**Comment by BioFUSION3k** [comment]
+1

**Comment by BioFUSION3k** [comment]
Example: I spent like 3-4 hours writing all those macros without the All Filters selection, it's taking just as long to re-make them with the All Filters selection because I have to delete each Action individually, make sure im not deleting the good ones so have to go slowly, I think a multi-select is needed at this stage. Im game for either checkbox/cntrl + click.

I have also at times found myself doing something similar in another scene, and would find a copy/paste ability a huge time saver.
