### ISSUE TITLE
[Feature Request] Better Motion Detection Scene Switching?

### ISSUE THREAD

**Issue by Wojeck** [WarmUpTill/SceneSwitcher#904]
MY PROBLEM & EXAMPLE:
In my use case, the issue I encounter is that there's an inherent capability to automatically switch scenes when a change in the current or previous scene occurs. This is accomplished with some straightforward logic within Advanced Scene Switcher. While it's a valuable feature for those who need it, as exemplified in the use case from the wiki. it becomes problematic when you don't require this kind of scene switching when trying to use a Motion Detection workflow, which is precisely the situation I'm facing.

To illustrate my use case, consider a DIY CCTV setup. As an individual moves from one room to another, OBS will detect motion in the new room and will switch the scene accordingly.

MY SOLUTION:
Empowering Advanced Scene Switcher to switch to any scene that detects motion using pattern matching, regardless of whether those scenes are presently selected in the scene tab, would provide a more flexible solution. This would remove the constraints imposed by the limited choices of "Current Scene," "Previous Scene," and "Preview Scene."

I believe that accomplishing this could be done by expanding the selection of choices within the Video category, extending beyond the existing "Current Scene," "Previous Scene," and "Preview Scene" options.

To elaborate further, my desired outcome is to have the capability to switch to any scene that has detected motion without being confined to the linear constraints that scene switching presents in the current release of the Advanced Scene Switcher.

MY SHITTY PAINT EXAMPLE:
My situation isn't exactly the same, as I'm dealing with a warehouse, but you get the idea.
![E G](https://github.com/WarmUpTill/SceneSwitcher/assets/64199488/476e1ed9-d835-4414-8fd3-069987756d78)

**Comment by WarmUpTill** [comment]
I understand what you are trying to achieve, but am still struggling a bit with understanding what is currently preventing you from getting this to work.

Can you not simply setup something similar to this?
 * Macro 1: If Video [Camera 1 scene] motion detected => switch to scene [Camera 1 scene]
* Macro 2: If Video [Camera 2 scene] motion detected => switch to scene [Camera 2 scene]
 * Macro 3: If Video [Camera 2 scene] motion detected => switch to scene [Camera 3 scene]
 * ...

Is the issue you are running into maybe the one described here:
https://github.com/WarmUpTill/SceneSwitcher/wiki/Video-condition#important-note
So summarized: A video source (which includes scenes) which is not "visible" is not rendered by OBS.
Thus the plugin cannot check for changes.
You can work around this by opening "Windowed Projector" windows of the scenes so that they are always rendered, even if they are not currently selected as OBS' main scene.

**Comment by WarmUpTill** [comment]
I will close this for now.
Let me know if you need further support! :)
