### ISSUE TITLE
Glitching "set to fixed value" field

### ISSUE THREAD

**Issue by Destroy666x** [WarmUpTill/SceneSwitcher#955]
**Describe the bug**
I have the following action:
![image](https://github.com/WarmUpTill/SceneSwitcher/assets/3606072/facca986-16c3-4336-91d1-f73ebabf7d17)

Once I type anything else into that field, the input scrolls to some empty line and no text can be seen.

**To Reproduce**
1. Create action like above
2. Try to type additional text in e.g. the middle or by the end of it.

**Expected behavior**
It shouldn't scroll/glitch.

**Logs**
Don't think they're needed, but let me know and I'll add them if so.

**Version information**
 - OS: Windows 10
 - OBS Version 30.0.2
 - Plugin Version dev: master

**Additional context**

**Comment by WarmUpTill** [comment]
Thanks for pointing that out!

To be honest I have no clue what is going on there.
After lots of trial and error I have reworked how the ResizingPlainTextEdit handles new text being entered to work around this. (https://github.com/WarmUpTill/SceneSwitcher/pull/952/commits/af946c8052820905136954185613482586ea4a3a)
It is not perfect due to some flickering happening in the scenarios, where this bug would previously occur, but hopefully still an improvement, since the text no longer seems to disappear from the view.

**Comment by Destroy666x** [comment]
Finally got to test it and seems fine, I noticed no flickering so far at least.
