### ISSUE TITLE
[Bug Report] "Change Scene" dropdowns don't work properly

### ISSUE THREAD

**Issue by MinecraftNight4** [WarmUpTill/SceneSwitcher#958]
**Describe the bug**
For some reason when selecting the "Change Scene" action, the interface does not adapt correctly to fit the plugin translation.

**To Reproduce**
1. Create a macro
2. Create an action of the type "Change Scene".
3. In "program" mode, it is almost impossible to open the dropdowns.

**Logs**
https://obsproject.com/logs/So8MZLVB1XcIML6L

**Version information**
 - OS: Windows 10
 - OBS Version 30.0.2
 - Plugin Version 1.24.2

**Additional context**

https://github.com/WarmUpTill/SceneSwitcher/assets/42017416/5ddf77c5-d761-4499-bbe8-30cf71bd03d7

**Comment by WarmUpTill** [comment]
Yeah that is a good point.
I changed the behaviour to display a horizontal scroll bar instead of squashing the widgets below a sensible minimum size.

![Example](https://github.com/WarmUpTill/SceneSwitcher/assets/19472752/ab0d7f7d-b926-45a2-89ab-5137542c2265)

A build with this change will be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/7343667306

**Comment by MinecraftNight4** [comment]
With the changes made, dropdowns now work correctly.
There are only some small problem when dragging sliders, which cause events/actions to be dragged.

https://github.com/WarmUpTill/SceneSwitcher/assets/42017416/2017e917-83a0-4997-bff4-fdf72d11139c

**Comment by WarmUpTill** [comment]
Should be fixed with this build:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/7365210093?pr=963

Thanks! :)

**Comment by MinecraftNight4** [comment]
Everything is working!
https://github.com/WarmUpTill/SceneSwitcher/assets/42017416/58b95b87-4a96-4930-8726-f217f69f140e
