### ISSUE TITLE
Scene Item Visibility "is visible" not working as expected for Image Slide Show

### ISSUE THREAD

**Issue by miko3ed** [WarmUpTill/SceneSwitcher#968]
**Describe the bug**
I am seeing a strange behavior where "is visible" is not working as expected for the Image Slide Show source when using the "Source of Type" parameter, specifically for IF statements.

**To Reproduce**
1. Create a new Scene with a placeholder IMAGE and IMAGE SLIDE SHOW source
2. Create a new Macro
3. Set the IF condition for "Scene Item Visibility" and select your scene where the above placeholder images are
4. Select "Sources of Type" and "Image Slide Show" for parameters.
5. Turning source visibility on and off in your scene does not trigger the IF statement.

**Version information**
 - OS: [e.g. Windows 11]
 - OBS Version [e.g. 30.0.2]
 - Plugin Version [e.g. 1.24.2]

**Additional context**
If you use IF NOT and "is hidden" instead it works as expected. This behavior also is not replicated with the IMAGE source type. See the attached images and video to help explain the issue. The video first shows the "IF NOT/is hidden" combination functioning as expected and then altering the parameters to be "IF/is visible" and not functioning as expected for IMAGE SLIDE SHOW sources.

![Screenshot 2024-01-03 134826](https://github.com/WarmUpTill/SceneSwitcher/assets/6305342/9d150907-f768-4407-b12b-5d90e8c8f9fb)
![Screenshot 2024-01-03 134954](https://github.com/WarmUpTill/SceneSwitcher/assets/6305342/be9dfbc0-7b23-4f72-8427-7513461055df)
[2024-01-03 13-51-51_1.webm](https://github.com/WarmUpTill/SceneSwitcher/assets/6305342/c83a3aff-b0b8-4eec-ac50-55cb0a455c89)

**Comment by WarmUpTill** [comment]
If you select "Source type" as the as the input for the scene item visibility condition _all_ sources of that type must meet the selected criteria on the selected scene.

This explains why "if not ... hidden" does not equal "if ... visible", since "if not four out of four sources are hidden" is not the same as "if four out of four sources are visible".

I hope that explains the unexpected behaviour! :)
I will try to make this more clear somehow.

**Comment by miko3ed** [comment]
Oh I see, I understand now, thanks for the clarification
