### ISSUE TITLE
Sequence stops after first switch when streaming

### ISSUE THREAD

**Issue by Katzyh** [WarmUpTill/SceneSwitcher#980]
**Describe the bug**
I have a sequence of different camera angles i want to use. Everything works in my sequence as it should until i start streaming. Then plugin stops working after first switch in sequence.  If i stop streaming then sequence starts to work normally as it should. 

**To Reproduce**

Set up a sequence of cameras.
Start streaming
You will see sequence stops after first switch ( only when streaming)

**Expected behavior**

**Logs**

Please provide a log of your issue with verbose logging enabled (See General tab of the plugin).  
In case of a crash, please also include the corresponding crash log.  
See [here](https://obsproject.com/forum/threads/please-post-a-log-with-your-issue-heres-how.23074/) for a description where to find the log files and how to share them.  
Please share the currently used plugin settings by exporting them them to a file (See General tab of the plugin).  

https://obsproject.com/logs/hTRTP6XhogEy3BIG

[adv-ss-1080p-2024.01.10.03.30.40.txt](https://github.com/WarmUpTill/SceneSwitcher/files/13881787/adv-ss-1080p-2024.01.10.03.30.40.txt)

**Version information**
 - Win 11
 - OBS Version [30.0.2]
 - Plugin Version [1.24.0]

**Additional context**

**Comment by WarmUpTill** [comment]
You are (probably unintentionally) mixing macros with the "old" non macro tabs.
This is something I would *not* recommend.

You have configured the plugin to prioritize the "macro" tab to have priority over the old "Sequence" tab (which is fine).

But you have also configured a macro which checks if you are currently streaming and then does nothing.
Since a macro was found which matched the "Sequence" tab is no longer checked.

---

The easiest way to resolve your issue is to delete your macros as they don't seem to serve any purpose anyway.
The other option would be to ditch the old tabs in favour of the macro tab. (This is what I would do, but that is up to you)

Let me know if you have any questions! :)

**Comment by Katzyh** [comment]
This helped! 
Many thanks :)
